name: api_utils
description: Convenient api utilities to make working with REST APIs easier
version: 2.0.0-nullsafety.0
homepage: https://github.com/HomeXLabs/api_utils
repository: https://github.com/HomeXLabs/api_utils

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  http: '>=0.12.0 <1.0.0'
  meta: '>=1.0.0 <2.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: