name: api_utils
description: Simple api utilities to make working with REST easier
version: 0.0.1
homepage: https://github.com/HomeXLabs/api_utils

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  http: '>=0.12.0 <1.0.0'
  meta: '>=1.0.0 <2.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: